---

- name: copy zip file
  copy:
    src: files/artifact.tar.gz
    dest: ~/artifact.tar.gz
    backup: yes

- name: extract file
  shell: | 
    tar -zxvf artifact.tar.gz

- name: install dependency
  shell: |
    npm install

- name: Restart node
  shell: |
    pm2 start npm -- start